baseURL: https://ckscks038038.github.io/blog/
languageCode: en-us
title: Lutein 40g
theme: PaperMod

params:
  homeInfoParams:
    Title: 'Hello! This is Lutein 40g'
    Content: 'Welcome to our blog, it is a spot where we jot down our random thoughts and ideas.'

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      
params:
    profileMode:
        enabled: true
        title: "Lutein 40g" # optional default will be site title
        subtitle: "This is subtitle"
        imageUrl: "/static/img/keyboard.png"
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 200 # custom size
        imageHeight: 200 # custom size
        buttons:
            - name: Github
              url: "https://github.com/"
            - name: Post
              url: "/post"
            - name: Resume
              url: "/resume.pdf"
            

    socialIcons: # optional
        - name: "<platform>"
          url: "<link>"
        - name: "<platform 2>"
          url: "public/CV_Hsuan-Yang Huang.pdf"
